from __future__ import annotations
from typing import Protocol

class BrokerBase(Protocol):
    def get_daily_ohlcv(self, symbol, lookback: int): ...
    def place_order(self, symbol, side: str, qty: float, order_type: str, price: float | None = None, market: str | None = None): ...
    def cancel_order(self, order_id: str): ...
    def modify_order(self, order_id: str, new_price: float | None = None, new_qty: float | None = None): ...
    def get_positions(self): ...
    def get_balance(self): ...
    def get_fills(self): ...
