SCHEMA = [
"""CREATE TABLE IF NOT EXISTS signals(signal_id TEXT PRIMARY KEY, symbol TEXT, side TEXT, score REAL, reason TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
"""CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id TEXT, symbol TEXT, side TEXT, qty INTEGER, price REAL, idempotency_key TEXT UNIQUE, state TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
"""CREATE TABLE IF NOT EXISTS fills(id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER, qty INTEGER, price REAL, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
"""CREATE TABLE IF NOT EXISTS positions(id INTEGER PRIMARY KEY AUTOINCREMENT, symbol TEXT, qty INTEGER, avg_price REAL, state TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
"""CREATE TABLE IF NOT EXISTS errors(id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT, message TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
]
